prg_comment = ""
prg_version = "0.7"
def program(prg, cmd):
    prg.add(-12000, "Probe_pulse_cleaning")
    prg.add(-10000, "Switch Off Dipole", enable=False)
    prg.add(-5000, "AOM Probe Detuning", -1.000, functions=dict(frequency=lambda x: cmd.get_var('probe_det'), funct_enable=False))
    prg.add(-130, "TTL uW 1 (100W) OFF")
    prg.add(-120, "TTL uW 2 OFF")
    prg.add(0, "magnetization_imaging")
    prg.add(250, "Oscilloscope Trigger ON", enable=False)
    prg.add(20250, "TTL Picture Hamamatsu  ON", 'beating_0', enable=False)
    prg.add(30140, "Oscilloscope Trigger ON", enable=False)
    prg.add(30150, "interferometer", enable=False)
    prg.add(30250, "hamam_twofastpictures", enable=False)
    prg.add(35250, "TTL Picture Hamamatsu  ON", 'beating_1', enable=False)
    prg.add(36350, "transfer_m1to0", enable=False)
    prg.add(36350, "transfer_0to0", enable=False)
    prg.add(36350, "interferometer_2", enable=False)
    prg.add(40250, "TTL uW 2 ON", enable=False)
    prg.add(150250, "TTL Picture Hamamatsu  ON", 'PTAI_probe')
    prg.add(151250, "Probe_pulse_Hamam")
    prg.add(200250, "TTL Picture Hamamatsu  ON", 'PTAI_back')
    prg.add(202250, "TTL Picture Hamamatsu OFF")
    prg.add(210250, "AOM Probe Detuning", 100.000)
    return prg
