prg_comment = ""
prg_version = "0.5.1"
def program(prg, cmd):
    prg.add(-2805000, "Shutter RepumperMOT ON")
    prg.add(-2290000, "AOM Repumper Amp", 1000)
    prg.add(-2280000, "AOM Repumper freq", 225.00)
    prg.add(-2272500, "AOM Probe Amp ch2 (-)", 1)
    prg.add(-2270000, "AOM Probe Amp ch1 (+)", 1)
    prg.add(-2263000, "Shutter Probe ON")
    prg.add(-2000000, "DAC Magnetic Trap Voltage", 0.0000, functions=dict(value=lambda x: x + x + 0.7*cmd.get_var('I')))
    prg.add(0, "Config field gradient to levit")
    prg.add(0, "Config field OFF", enable=False)
    prg.add(1500, "DAC Magnetic Trap current", 0.0000, functions=dict(value=lambda x: x + cmd.get_var('I')))
    prg.add(2500, "IGBT BCompY field CLOSE")
    prg.add(5000, "BCompY current ramp", start_t=0, stop_x=5, n_points=50, start_x=0, stop_t=7, enable=False)
    prg.add(84500, "IGBT BCompY field OPEN", functions=dict(time=lambda x: x + cmd.get_var('dt')), enable=False)
    prg.add(100000, "Config field OFF", functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(102000, "AOM Probe Detuning", 0.000, functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(102800, "AOM DS + RepumperMOT Amp ", 1000, functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(103000, "AOM DS + RepumperMOT Freq", 408.00, functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(103300, "TTL Repumper MOT  ON", functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(113700, "TTL Repumper MOT OFF", functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(113750, "AOM DS + RepumperMOT Amp ", 1, functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(114700, "TTL Picture  ON", functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(115100, "AOM Probe Amp ch1 (+)", 1000, functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(115500, "AOM Probe Amp ch2 (-)", 600, functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(116500, "AOM Probe Amp ch2 (-)", 1, functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(116900, "AOM Probe Amp ch1 (+)", 1, functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(117300, "TTL Picture OFF", functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(865300, "Shutter Probe OFF", functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(1124200, "TTL Picture  ON", functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(1124600, "AOM Probe Amp ch1 (+)", 1000, functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(1125000, "AOM Probe Amp ch2 (-)", 1000, functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(1126000, "AOM Probe Amp ch2 (-)", 1, functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(1126400, "AOM Probe Amp ch1 (+)", 1, functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(1126800, "TTL Picture OFF", functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(1134800, "TTL Repumper MOT OFF", functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(2124300, "TTL Picture  ON", functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(2127100, "TTL Picture OFF", functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(3125100, "TTL Picture  ON", functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(3127900, "TTL Picture OFF", functions=dict(time=lambda x: x + cmd.get_var('dt')))
    prg.add(3128500, "IGBT BCompY field OPEN", functions=dict(time=lambda x: x + cmd.get_var('dt')))
    return prg
